### ISSUE TITLE
Infografía de Realidad Aumentada

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/infografia-Jaci14#1]
<img width="600" alt="1" src="https://user-images.githubusercontent.com/79876660/153735095-c0ba8d89-4145-4758-b194-299f67e9d83c.png">
<img width="600" alt="1(1)" src="https://user-images.githubusercontent.com/79876660/153735984-ba34e03e-e156-4090-bef4-32d597657277.png">

**Comment by josealfredo79** [comment]
Bien hecho y revisado
