### ISSUE TITLE
Infografía Ingeniería de Requisitos

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/infografia-Jaci14#2]
![Infografia Jaciel García Santiago 1](https://user-images.githubusercontent.com/79876660/109920021-45487780-7c7f-11eb-80e5-49de80976557.png)
![Infografia Jaciel García Santiago 2](https://user-images.githubusercontent.com/79876660/109920024-47123b00-7c7f-11eb-90cb-9cf9c4b55d35.png)

**Comment by ElvisS10** [comment]
Excelente trabajo 💯! Muy bien realizado la infografía y muy bien detallado los puntos de la Ingeniera de requisitos.
**Calificación: 20%**

**Comment by ThorSampy** [comment]
El trabajo esta muy bien elaborado y cuenta con los puntos establecidos en la rubrica.

**Comment by Anna-Aparicio** [comment]
Trabajo bien elaborado,  coherencia y muy buena distribución de imágenes y texto

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
